// Elementum — Periodic Table Data
// All 118 elements with properties for QUIC0001 UTEM

const ELEMENTS = [
  // Period 1
  { z: 1, symbol: "H", name: "Hidrógeno", mass: 1.008, period: 1, group: 1, block: "s", category: "no-metal", electronegativity: 2.20, atomicRadius: 53, atomicVolume: 14.4, ionizationEnergy: 1312, electronAffinity: 72.8, electronConfig: "1s¹", valenceElectrons: 1, typicalBond: "covalente" },
  { z: 2, symbol: "He", name: "Helio", mass: 4.003, period: 1, group: 18, block: "s", category: "gas-noble", electronegativity: null, atomicRadius: 31, atomicVolume: 31.8, ionizationEnergy: 2372, electronAffinity: -48, electronConfig: "1s²", valenceElectrons: 2, typicalBond: "ninguno", dataQuality: { electronAffinity: "experimental" } },

  // Period 2
  { z: 3, symbol: "Li", name: "Litio", mass: 6.941, period: 2, group: 1, block: "s", category: "metal-alcalino", electronegativity: 0.98, atomicRadius: 167, atomicVolume: 13.1, ionizationEnergy: 520, electronAffinity: 59.6, electronConfig: "1s² 2s¹", valenceElectrons: 1, typicalBond: "iónico" },
  { z: 4, symbol: "Be", name: "Berilio", mass: 9.012, period: 2, group: 2, block: "s", category: "metal-alcalinoterreo", electronegativity: 1.57, atomicRadius: 112, atomicVolume: 4.9, ionizationEnergy: 900, electronAffinity: -48, electronConfig: "1s² 2s²", valenceElectrons: 2, typicalBond: "metálico", dataQuality: { electronAffinity: "experimental" } },
  { z: 5, symbol: "B", name: "Boro", mass: 10.811, period: 2, group: 13, block: "p", category: "metaloide", electronegativity: 2.04, atomicRadius: 87, atomicVolume: 4.6, ionizationEnergy: 801, electronAffinity: 26.7, electronConfig: "1s² 2s² 2p¹", valenceElectrons: 3, typicalBond: "covalente" },
  { z: 6, symbol: "C", name: "Carbono", mass: 12.011, period: 2, group: 14, block: "p", category: "no-metal", electronegativity: 2.55, atomicRadius: 67, atomicVolume: 5.3, ionizationEnergy: 1086, electronAffinity: 121.8, electronConfig: "1s² 2s² 2p²", valenceElectrons: 4, typicalBond: "covalente" },
  { z: 7, symbol: "N", name: "Nitrógeno", mass: 14.007, period: 2, group: 15, block: "p", category: "no-metal", electronegativity: 3.04, atomicRadius: 56, atomicVolume: 17.3, ionizationEnergy: 1402, electronAffinity: -7, electronConfig: "1s² 2s² 2p³", valenceElectrons: 5, typicalBond: "covalente", dataQuality: { electronAffinity: "experimental" } },
  { z: 8, symbol: "O", name: "Oxígeno", mass: 15.999, period: 2, group: 16, block: "p", category: "no-metal", electronegativity: 3.44, atomicRadius: 48, atomicVolume: 14.0, ionizationEnergy: 1314, electronAffinity: 141.0, electronConfig: "1s² 2s² 2p⁴", valenceElectrons: 6, typicalBond: "covalente" },
  { z: 9, symbol: "F", name: "Flúor", mass: 18.998, period: 2, group: 17, block: "p", category: "halogeno", electronegativity: 3.98, atomicRadius: 42, atomicVolume: 17.1, ionizationEnergy: 1681, electronAffinity: 328.2, electronConfig: "1s² 2s² 2p⁵", valenceElectrons: 7, typicalBond: "iónico" },
  { z: 10, symbol: "Ne", name: "Neón", mass: 20.180, period: 2, group: 18, block: "p", category: "gas-noble", electronegativity: null, atomicRadius: 38, atomicVolume: 16.8, ionizationEnergy: 2081, electronAffinity: -116, electronConfig: "1s² 2s² 2p⁶", valenceElectrons: 8, typicalBond: "ninguno", dataQuality: { electronAffinity: "experimental" } },

  // Period 3
  { z: 11, symbol: "Na", name: "Sodio", mass: 22.990, period: 3, group: 1, block: "s", category: "metal-alcalino", electronegativity: 0.93, atomicRadius: 190, atomicVolume: 23.7, ionizationEnergy: 496, electronAffinity: 52.8, electronConfig: "[Ne] 3s¹", valenceElectrons: 1, typicalBond: "iónico" },
  { z: 12, symbol: "Mg", name: "Magnesio", mass: 24.305, period: 3, group: 2, block: "s", category: "metal-alcalinoterreo", electronegativity: 1.31, atomicRadius: 160, atomicVolume: 14.0, ionizationEnergy: 738, electronAffinity: -21, electronConfig: "[Ne] 3s²", valenceElectrons: 2, typicalBond: "metálico", dataQuality: { electronAffinity: "experimental" } },
  { z: 13, symbol: "Al", name: "Aluminio", mass: 26.982, period: 3, group: 13, block: "p", category: "metal-post-transicion", electronegativity: 1.61, atomicRadius: 143, atomicVolume: 10.0, ionizationEnergy: 578, electronAffinity: 41.8, electronConfig: "[Ne] 3s² 3p¹", valenceElectrons: 3, typicalBond: "metálico" },
  { z: 14, symbol: "Si", name: "Silicio", mass: 28.086, period: 3, group: 14, block: "p", category: "metaloide", electronegativity: 1.90, atomicRadius: 117, atomicVolume: 12.1, ionizationEnergy: 786, electronAffinity: 134.1, electronConfig: "[Ne] 3s² 3p²", valenceElectrons: 4, typicalBond: "covalente" },
  { z: 15, symbol: "P", name: "Fósforo", mass: 30.974, period: 3, group: 15, block: "p", category: "no-metal", electronegativity: 2.19, atomicRadius: 98, atomicVolume: 17.0, ionizationEnergy: 1012, electronAffinity: 72.0, electronConfig: "[Ne] 3s² 3p³", valenceElectrons: 5, typicalBond: "covalente" },
  { z: 16, symbol: "S", name: "Azufre", mass: 32.065, period: 3, group: 16, block: "p", category: "no-metal", electronegativity: 2.58, atomicRadius: 88, atomicVolume: 15.5, ionizationEnergy: 1000, electronAffinity: 200.4, electronConfig: "[Ne] 3s² 3p⁴", valenceElectrons: 6, typicalBond: "covalente" },
  { z: 17, symbol: "Cl", name: "Cloro", mass: 35.453, period: 3, group: 17, block: "p", category: "halogeno", electronegativity: 3.16, atomicRadius: 79, atomicVolume: 22.7, ionizationEnergy: 1251, electronAffinity: 348.6, electronConfig: "[Ne] 3s² 3p⁵", valenceElectrons: 7, typicalBond: "iónico" },
  { z: 18, symbol: "Ar", name: "Argón", mass: 39.948, period: 3, group: 18, block: "p", category: "gas-noble", electronegativity: null, atomicRadius: 71, atomicVolume: 28.5, ionizationEnergy: 1521, electronAffinity: -96, electronConfig: "[Ne] 3s² 3p⁶", valenceElectrons: 8, typicalBond: "ninguno", dataQuality: { electronAffinity: "experimental" } },

  // Period 4
  { z: 19, symbol: "K", name: "Potasio", mass: 39.098, period: 4, group: 1, block: "s", category: "metal-alcalino", electronegativity: 0.82, atomicRadius: 243, atomicVolume: 45.3, ionizationEnergy: 419, electronAffinity: 48.4, electronConfig: "[Ar] 4s¹", valenceElectrons: 1, typicalBond: "iónico" },
  { z: 20, symbol: "Ca", name: "Calcio", mass: 40.078, period: 4, group: 2, block: "s", category: "metal-alcalinoterreo", electronegativity: 1.00, atomicRadius: 194, atomicVolume: 29.9, ionizationEnergy: 590, electronAffinity: 2.37, electronConfig: "[Ar] 4s²", valenceElectrons: 2, typicalBond: "metálico" },
  { z: 21, symbol: "Sc", name: "Escandio", mass: 44.956, period: 4, group: 3, block: "d", category: "metal-transicion", electronegativity: 1.36, atomicRadius: 184, atomicVolume: 15.0, ionizationEnergy: 633, electronAffinity: 18.1, electronConfig: "[Ar] 3d¹ 4s²", valenceElectrons: 3, typicalBond: "metálico" },
  { z: 22, symbol: "Ti", name: "Titanio", mass: 47.867, period: 4, group: 4, block: "d", category: "metal-transicion", electronegativity: 1.54, atomicRadius: 176, atomicVolume: 10.6, ionizationEnergy: 659, electronAffinity: 7.6, electronConfig: "[Ar] 3d² 4s²", valenceElectrons: 4, typicalBond: "metálico" },
  { z: 23, symbol: "V", name: "Vanadio", mass: 50.942, period: 4, group: 5, block: "d", category: "metal-transicion", electronegativity: 1.63, atomicRadius: 171, atomicVolume: 8.3, ionizationEnergy: 651, electronAffinity: 50.6, electronConfig: "[Ar] 3d³ 4s²", valenceElectrons: 5, typicalBond: "metálico" },
  { z: 24, symbol: "Cr", name: "Cromo", mass: 51.996, period: 4, group: 6, block: "d", category: "metal-transicion", electronegativity: 1.66, atomicRadius: 166, atomicVolume: 7.2, ionizationEnergy: 653, electronAffinity: 64.3, electronConfig: "[Ar] 3d⁵ 4s¹", valenceElectrons: 6, typicalBond: "metálico" },
  { z: 25, symbol: "Mn", name: "Manganeso", mass: 54.938, period: 4, group: 7, block: "d", category: "metal-transicion", electronegativity: 1.55, atomicRadius: 161, atomicVolume: 7.4, ionizationEnergy: 717, electronAffinity: -50, electronConfig: "[Ar] 3d⁵ 4s²", valenceElectrons: 7, typicalBond: "metálico", dataQuality: { electronAffinity: "experimental" } },
  { z: 26, symbol: "Fe", name: "Hierro", mass: 55.845, period: 4, group: 8, block: "d", category: "metal-transicion", electronegativity: 1.83, atomicRadius: 156, atomicVolume: 7.1, ionizationEnergy: 763, electronAffinity: 15.7, electronConfig: "[Ar] 3d⁶ 4s²", valenceElectrons: 8, typicalBond: "metálico" },
  { z: 27, symbol: "Co", name: "Cobalto", mass: 58.933, period: 4, group: 9, block: "d", category: "metal-transicion", electronegativity: 1.88, atomicRadius: 152, atomicVolume: 6.7, ionizationEnergy: 760, electronAffinity: 63.7, electronConfig: "[Ar] 3d⁷ 4s²", valenceElectrons: 9, typicalBond: "metálico" },
  { z: 28, symbol: "Ni", name: "Níquel", mass: 58.693, period: 4, group: 10, block: "d", category: "metal-transicion", electronegativity: 1.91, atomicRadius: 149, atomicVolume: 6.6, ionizationEnergy: 737, electronAffinity: 112.0, electronConfig: "[Ar] 3d⁸ 4s²", valenceElectrons: 10, typicalBond: "metálico" },
  { z: 29, symbol: "Cu", name: "Cobre", mass: 63.546, period: 4, group: 11, block: "d", category: "metal-transicion", electronegativity: 1.90, atomicRadius: 145, atomicVolume: 7.1, ionizationEnergy: 746, electronAffinity: 118.4, electronConfig: "[Ar] 3d¹⁰ 4s¹", valenceElectrons: 1, typicalBond: "metálico" },
  { z: 30, symbol: "Zn", name: "Zinc", mass: 65.38, period: 4, group: 12, block: "d", category: "metal-transicion", electronegativity: 1.65, atomicRadius: 142, atomicVolume: 9.2, ionizationEnergy: 906, electronAffinity: -58, electronConfig: "[Ar] 3d¹⁰ 4s²", valenceElectrons: 2, typicalBond: "metálico", dataQuality: { electronAffinity: "experimental" } },
  { z: 31, symbol: "Ga", name: "Galio", mass: 69.723, period: 4, group: 13, block: "p", category: "metal-post-transicion", electronegativity: 1.81, atomicRadius: 136, atomicVolume: 11.8, ionizationEnergy: 579, electronAffinity: 29.1, electronConfig: "[Ar] 3d¹⁰ 4s² 4p¹", valenceElectrons: 3, typicalBond: "metálico" },
  { z: 32, symbol: "Ge", name: "Germanio", mass: 72.630, period: 4, group: 14, block: "p", category: "metaloide", electronegativity: 2.01, atomicRadius: 125, atomicVolume: 13.6, ionizationEnergy: 762, electronAffinity: 119.0, electronConfig: "[Ar] 3d¹⁰ 4s² 4p²", valenceElectrons: 4, typicalBond: "covalente" },
  { z: 33, symbol: "As", name: "Arsénico", mass: 74.922, period: 4, group: 15, block: "p", category: "metaloide", electronegativity: 2.18, atomicRadius: 114, atomicVolume: 13.1, ionizationEnergy: 947, electronAffinity: 78.2, electronConfig: "[Ar] 3d¹⁰ 4s² 4p³", valenceElectrons: 5, typicalBond: "covalente" },
  { z: 34, symbol: "Se", name: "Selenio", mass: 78.971, period: 4, group: 16, block: "p", category: "no-metal", electronegativity: 2.55, atomicRadius: 103, atomicVolume: 16.5, ionizationEnergy: 941, electronAffinity: 195.0, electronConfig: "[Ar] 3d¹⁰ 4s² 4p⁴", valenceElectrons: 6, typicalBond: "covalente" },
  { z: 35, symbol: "Br", name: "Bromo", mass: 79.904, period: 4, group: 17, block: "p", category: "halogeno", electronegativity: 2.96, atomicRadius: 94, atomicVolume: 23.5, ionizationEnergy: 1140, electronAffinity: 324.6, electronConfig: "[Ar] 3d¹⁰ 4s² 4p⁵", valenceElectrons: 7, typicalBond: "iónico" },
  { z: 36, symbol: "Kr", name: "Kriptón", mass: 83.798, period: 4, group: 18, block: "p", category: "gas-noble", electronegativity: null, atomicRadius: 88, atomicVolume: 38.9, ionizationEnergy: 1351, electronAffinity: -96, electronConfig: "[Ar] 3d¹⁰ 4s² 4p⁶", valenceElectrons: 8, typicalBond: "ninguno", dataQuality: { electronAffinity: "experimental" } },

  // Period 5
  { z: 37, symbol: "Rb", name: "Rubidio", mass: 85.468, period: 5, group: 1, block: "s", category: "metal-alcalino", electronegativity: 0.82, atomicRadius: 265, atomicVolume: 55.9, ionizationEnergy: 403, electronAffinity: 46.9, electronConfig: "[Kr] 5s¹", valenceElectrons: 1, typicalBond: "iónico" },
  { z: 38, symbol: "Sr", name: "Estroncio", mass: 87.620, period: 5, group: 2, block: "s", category: "metal-alcalinoterreo", electronegativity: 0.95, atomicRadius: 219, atomicVolume: 33.7, ionizationEnergy: 550, electronAffinity: 5.03, electronConfig: "[Kr] 5s²", valenceElectrons: 2, typicalBond: "metálico" },
  { z: 39, symbol: "Y", name: "Itrio", mass: 88.906, period: 5, group: 3, block: "d", category: "metal-transicion", electronegativity: 1.22, atomicRadius: 212, atomicVolume: 19.8, ionizationEnergy: 600, electronAffinity: 29.6, electronConfig: "[Kr] 4d¹ 5s²", valenceElectrons: 3, typicalBond: "metálico" },
  { z: 40, symbol: "Zr", name: "Zirconio", mass: 91.224, period: 5, group: 4, block: "d", category: "metal-transicion", electronegativity: 1.33, atomicRadius: 206, atomicVolume: 14.1, ionizationEnergy: 640, electronAffinity: 41.1, electronConfig: "[Kr] 4d² 5s²", valenceElectrons: 4, typicalBond: "metálico" },
  { z: 41, symbol: "Nb", name: "Niobio", mass: 92.906, period: 5, group: 5, block: "d", category: "metal-transicion", electronegativity: 1.60, atomicRadius: 198, atomicVolume: 10.8, ionizationEnergy: 652, electronAffinity: 86.1, electronConfig: "[Kr] 4d⁴ 5s¹", valenceElectrons: 5, typicalBond: "metálico" },
  { z: 42, symbol: "Mo", name: "Molibdeno", mass: 95.960, period: 5, group: 6, block: "d", category: "metal-transicion", electronegativity: 2.16, atomicRadius: 190, atomicVolume: 9.4, ionizationEnergy: 684, electronAffinity: 71.9, electronConfig: "[Kr] 4d⁵ 5s¹", valenceElectrons: 6, typicalBond: "metálico" },
  { z: 43, symbol: "Tc", name: "Tecnecio", mass: 98.000, period: 5, group: 7, block: "d", category: "metal-transicion", electronegativity: 1.90, atomicRadius: 183, atomicVolume: 8.5, ionizationEnergy: 702, electronAffinity: 53.0, electronConfig: "[Kr] 4d⁵ 5s²", valenceElectrons: 7, typicalBond: "metálico" },
  { z: 44, symbol: "Ru", name: "Rutenio", mass: 101.070, period: 5, group: 8, block: "d", category: "metal-transicion", electronegativity: 2.20, atomicRadius: 178, atomicVolume: 8.2, ionizationEnergy: 710, electronAffinity: 101.3, electronConfig: "[Kr] 4d⁷ 5s¹", valenceElectrons: 8, typicalBond: "metálico" },
  { z: 45, symbol: "Rh", name: "Rodio", mass: 102.906, period: 5, group: 9, block: "d", category: "metal-transicion", electronegativity: 2.28, atomicRadius: 173, atomicVolume: 8.3, ionizationEnergy: 720, electronAffinity: 109.7, electronConfig: "[Kr] 4d⁸ 5s¹", valenceElectrons: 9, typicalBond: "metálico" },
  { z: 46, symbol: "Pd", name: "Paladio", mass: 106.420, period: 5, group: 10, block: "d", category: "metal-transicion", electronegativity: 2.20, atomicRadius: 169, atomicVolume: 8.9, ionizationEnergy: 805, electronAffinity: 53.7, electronConfig: "[Kr] 4d¹⁰", valenceElectrons: 10, typicalBond: "metálico" },
  { z: 47, symbol: "Ag", name: "Plata", mass: 107.868, period: 5, group: 11, block: "d", category: "metal-transicion", electronegativity: 1.93, atomicRadius: 165, atomicVolume: 10.3, ionizationEnergy: 731, electronAffinity: 125.6, electronConfig: "[Kr] 4d¹⁰ 5s¹", valenceElectrons: 1, typicalBond: "metálico" },
  { z: 48, symbol: "Cd", name: "Cadmio", mass: 112.411, period: 5, group: 12, block: "d", category: "metal-transicion", electronegativity: 1.69, atomicRadius: 161, atomicVolume: 13.0, ionizationEnergy: 868, electronAffinity: -56, electronConfig: "[Kr] 4d¹⁰ 5s²", valenceElectrons: 2, typicalBond: "metálico", dataQuality: { electronAffinity: "experimental" } },
  { z: 49, symbol: "In", name: "Indio", mass: 114.818, period: 5, group: 13, block: "p", category: "metal-post-transicion", electronegativity: 1.78, atomicRadius: 156, atomicVolume: 15.7, ionizationEnergy: 558, electronAffinity: 29.0, electronConfig: "[Kr] 4d¹⁰ 5s² 5p¹", valenceElectrons: 3, typicalBond: "metálico" },
  { z: 50, symbol: "Sn", name: "Estaño", mass: 118.710, period: 5, group: 14, block: "p", category: "metal-post-transicion", electronegativity: 1.96, atomicRadius: 145, atomicVolume: 16.3, ionizationEnergy: 709, electronAffinity: 107.3, electronConfig: "[Kr] 4d¹⁰ 5s² 5p²", valenceElectrons: 4, typicalBond: "metálico" },
  { z: 51, symbol: "Sb", name: "Antimonio", mass: 121.760, period: 5, group: 15, block: "p", category: "metaloide", electronegativity: 2.05, atomicRadius: 133, atomicVolume: 18.4, ionizationEnergy: 834, electronAffinity: 101.1, electronConfig: "[Kr] 4d¹⁰ 5s² 5p³", valenceElectrons: 5, typicalBond: "covalente" },
  { z: 52, symbol: "Te", name: "Teluro", mass: 127.600, period: 5, group: 16, block: "p", category: "metaloide", electronegativity: 2.10, atomicRadius: 123, atomicVolume: 20.5, ionizationEnergy: 869, electronAffinity: 190.2, electronConfig: "[Kr] 4d¹⁰ 5s² 5p⁴", valenceElectrons: 6, typicalBond: "covalente" },
  { z: 53, symbol: "I", name: "Yodo", mass: 126.904, period: 5, group: 17, block: "p", category: "halogeno", electronegativity: 2.66, atomicRadius: 115, atomicVolume: 25.7, ionizationEnergy: 1008, electronAffinity: 295.2, electronConfig: "[Kr] 4d¹⁰ 5s² 5p⁵", valenceElectrons: 7, typicalBond: "iónico" },
  { z: 54, symbol: "Xe", name: "Xenón", mass: 131.293, period: 5, group: 18, block: "p", category: "gas-noble", electronegativity: null, atomicRadius: 108, atomicVolume: 42.9, ionizationEnergy: 1170, electronAffinity: -77, electronConfig: "[Kr] 4d¹⁰ 5s² 5p⁶", valenceElectrons: 8, typicalBond: "ninguno", dataQuality: { electronAffinity: "experimental" } },

  // Period 6
  { z: 55, symbol: "Cs", name: "Cesio", mass: 132.905, period: 6, group: 1, block: "s", category: "metal-alcalino", electronegativity: 0.79, atomicRadius: 298, atomicVolume: 70.0, ionizationEnergy: 376, electronAffinity: 45.5, electronConfig: "[Xe] 6s¹", valenceElectrons: 1, typicalBond: "iónico" },
  { z: 56, symbol: "Ba", name: "Bario", mass: 137.327, period: 6, group: 2, block: "s", category: "metal-alcalinoterreo", electronegativity: 0.89, atomicRadius: 253, atomicVolume: 39.0, ionizationEnergy: 503, electronAffinity: 13.95, electronConfig: "[Xe] 6s²", valenceElectrons: 2, typicalBond: "metálico" },
  // Lanthanides (period 6, f-block)
  { z: 57, symbol: "La", name: "Lantano", mass: 138.905, period: 6, group: null, block: "f", category: "lantanido", electronegativity: 1.10, atomicRadius: 240, atomicVolume: 22.5, ionizationEnergy: 538, electronAffinity: 48.3, electronConfig: "[Xe] 5d¹ 6s²", valenceElectrons: 3, typicalBond: "metálico" },
  { z: 58, symbol: "Ce", name: "Cerio", mass: 140.116, period: 6, group: null, block: "f", category: "lantanido", electronegativity: 1.12, atomicRadius: 235, atomicVolume: 20.7, ionizationEnergy: 534, electronAffinity: 50.0, electronConfig: "[Xe] 4f¹ 5d¹ 6s²", valenceElectrons: 4, typicalBond: "metálico" },
  { z: 59, symbol: "Pr", name: "Praseodimio", mass: 140.908, period: 6, group: null, block: "f", category: "lantanido", electronegativity: 1.13, atomicRadius: 239, atomicVolume: 20.8, ionizationEnergy: 527, electronAffinity: 93, electronConfig: "[Xe] 4f³ 6s²", valenceElectrons: 3, typicalBond: "metálico", dataQuality: { electronAffinity: "estimado" } },
  { z: 60, symbol: "Nd", name: "Neodimio", mass: 144.242, period: 6, group: null, block: "f", category: "lantanido", electronegativity: 1.14, atomicRadius: 229, atomicVolume: 20.6, ionizationEnergy: 533, electronAffinity: 185, electronConfig: "[Xe] 4f⁴ 6s²", valenceElectrons: 3, typicalBond: "metálico", dataQuality: { electronAffinity: "estimado" } },
  { z: 61, symbol: "Pm", name: "Prometio", mass: 145.000, period: 6, group: null, block: "f", category: "lantanido", electronegativity: 1.13, atomicRadius: 236, atomicVolume: 20.2, ionizationEnergy: 540, electronAffinity: 129, electronConfig: "[Xe] 4f⁵ 6s²", valenceElectrons: 3, typicalBond: "metálico", dataQuality: { electronAffinity: "estimado" } },
  { z: 62, symbol: "Sm", name: "Samario", mass: 150.360, period: 6, group: null, block: "f", category: "lantanido", electronegativity: 1.17, atomicRadius: 229, atomicVolume: 19.9, ionizationEnergy: 545, electronAffinity: 162, electronConfig: "[Xe] 4f⁶ 6s²", valenceElectrons: 3, typicalBond: "metálico", dataQuality: { electronAffinity: "estimado" } },
  { z: 63, symbol: "Eu", name: "Europio", mass: 151.964, period: 6, group: null, block: "f", category: "lantanido", electronegativity: 1.20, atomicRadius: 233, atomicVolume: 28.9, ionizationEnergy: 547, electronAffinity: 116, electronConfig: "[Xe] 4f⁷ 6s²", valenceElectrons: 3, typicalBond: "metálico", dataQuality: { electronAffinity: "estimado" } },
  { z: 64, symbol: "Gd", name: "Gadolinio", mass: 157.250, period: 6, group: null, block: "f", category: "lantanido", electronegativity: 1.20, atomicRadius: 237, atomicVolume: 19.9, ionizationEnergy: 593, electronAffinity: 13, electronConfig: "[Xe] 4f⁷ 5d¹ 6s²", valenceElectrons: 3, typicalBond: "metálico", dataQuality: { electronAffinity: "estimado" } },
  { z: 65, symbol: "Tb", name: "Terbio", mass: 158.925, period: 6, group: null, block: "f", category: "lantanido", electronegativity: 1.10, atomicRadius: 221, atomicVolume: 19.2, ionizationEnergy: 566, electronAffinity: 112, electronConfig: "[Xe] 4f⁹ 6s²", valenceElectrons: 3, typicalBond: "metálico", dataQuality: { electronAffinity: "estimado" } },
  { z: 66, symbol: "Dy", name: "Disprosio", mass: 162.500, period: 6, group: null, block: "f", category: "lantanido", electronegativity: 1.22, atomicRadius: 229, atomicVolume: 19.0, ionizationEnergy: 573, electronAffinity: 33, electronConfig: "[Xe] 4f¹⁰ 6s²", valenceElectrons: 3, typicalBond: "metálico", dataQuality: { electronAffinity: "estimado" } },
  { z: 67, symbol: "Ho", name: "Holmio", mass: 164.930, period: 6, group: null, block: "f", category: "lantanido", electronegativity: 1.23, atomicRadius: 216, atomicVolume: 18.7, ionizationEnergy: 581, electronAffinity: 32, electronConfig: "[Xe] 4f¹¹ 6s²", valenceElectrons: 3, typicalBond: "metálico", dataQuality: { electronAffinity: "estimado" } },
  { z: 68, symbol: "Er", name: "Erbio", mass: 167.259, period: 6, group: null, block: "f", category: "lantanido", electronegativity: 1.24, atomicRadius: 235, atomicVolume: 18.4, ionizationEnergy: 589, electronAffinity: 30, electronConfig: "[Xe] 4f¹² 6s²", valenceElectrons: 3, typicalBond: "metálico", dataQuality: { electronAffinity: "estimado" } },
  { z: 69, symbol: "Tm", name: "Tulio", mass: 168.934, period: 6, group: null, block: "f", category: "lantanido", electronegativity: 1.25, atomicRadius: 227, atomicVolume: 18.1, ionizationEnergy: 597, electronAffinity: 99, electronConfig: "[Xe] 4f¹³ 6s²", valenceElectrons: 3, typicalBond: "metálico", dataQuality: { electronAffinity: "estimado" } },
  { z: 70, symbol: "Yb", name: "Iterbio", mass: 173.045, period: 6, group: null, block: "f", category: "lantanido", electronegativity: 1.10, atomicRadius: 242, atomicVolume: 24.8, ionizationEnergy: 603, electronAffinity: -2, electronConfig: "[Xe] 4f¹⁴ 6s²", valenceElectrons: 3, typicalBond: "metálico", dataQuality: { electronAffinity: "estimado" } },
  { z: 71, symbol: "Lu", name: "Lutecio", mass: 174.967, period: 6, group: null, block: "f", category: "lantanido", electronegativity: 1.27, atomicRadius: 221, atomicVolume: 17.8, ionizationEnergy: 524, electronAffinity: 33, electronConfig: "[Xe] 4f¹⁴ 5d¹ 6s²", valenceElectrons: 3, typicalBond: "metálico", dataQuality: { electronAffinity: "estimado" } },
  { z: 72, symbol: "Hf", name: "Hafnio", mass: 178.490, period: 6, group: 4, block: "d", category: "metal-transicion", electronegativity: 1.30, atomicRadius: 208, atomicVolume: 13.4, ionizationEnergy: 659, electronAffinity: -17, electronConfig: "[Xe] 4f¹⁴ 5d² 6s²", valenceElectrons: 4, typicalBond: "metálico", dataQuality: { electronAffinity: "experimental" } },
  { z: 73, symbol: "Ta", name: "Tántalo", mass: 180.948, period: 6, group: 5, block: "d", category: "metal-transicion", electronegativity: 1.50, atomicRadius: 200, atomicVolume: 10.9, ionizationEnergy: 761, electronAffinity: 31.0, electronConfig: "[Xe] 4f¹⁴ 5d³ 6s²", valenceElectrons: 5, typicalBond: "metálico" },
  { z: 74, symbol: "W", name: "Tungsteno", mass: 183.840, period: 6, group: 6, block: "d", category: "metal-transicion", electronegativity: 2.36, atomicRadius: 193, atomicVolume: 9.5, ionizationEnergy: 770, electronAffinity: 78.6, electronConfig: "[Xe] 4f¹⁴ 5d⁴ 6s²", valenceElectrons: 6, typicalBond: "metálico" },
  { z: 75, symbol: "Re", name: "Renio", mass: 186.207, period: 6, group: 7, block: "d", category: "metal-transicion", electronegativity: 1.90, atomicRadius: 188, atomicVolume: 8.9, ionizationEnergy: 760, electronAffinity: 14.5, electronConfig: "[Xe] 4f¹⁴ 5d⁵ 6s²", valenceElectrons: 7, typicalBond: "metálico" },
  { z: 76, symbol: "Os", name: "Osmio", mass: 190.230, period: 6, group: 8, block: "d", category: "metal-transicion", electronegativity: 2.20, atomicRadius: 185, atomicVolume: 8.4, ionizationEnergy: 840, electronAffinity: 106.1, electronConfig: "[Xe] 4f¹⁴ 5d⁶ 6s²", valenceElectrons: 8, typicalBond: "metálico" },
  { z: 77, symbol: "Ir", name: "Iridio", mass: 192.217, period: 6, group: 9, block: "d", category: "metal-transicion", electronegativity: 2.20, atomicRadius: 180, atomicVolume: 8.5, ionizationEnergy: 880, electronAffinity: 151.0, electronConfig: "[Xe] 4f¹⁴ 5d⁷ 6s²", valenceElectrons: 9, typicalBond: "metálico" },
  { z: 78, symbol: "Pt", name: "Platino", mass: 195.084, period: 6, group: 10, block: "d", category: "metal-transicion", electronegativity: 2.28, atomicRadius: 177, atomicVolume: 9.1, ionizationEnergy: 870, electronAffinity: 205.3, electronConfig: "[Xe] 4f¹⁴ 5d⁹ 6s¹", valenceElectrons: 10, typicalBond: "metálico" },
  { z: 79, symbol: "Au", name: "Oro", mass: 196.967, period: 6, group: 11, block: "d", category: "metal-transicion", electronegativity: 2.54, atomicRadius: 174, atomicVolume: 10.2, ionizationEnergy: 890, electronAffinity: 222.8, electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹", valenceElectrons: 1, typicalBond: "metálico" },
  { z: 80, symbol: "Hg", name: "Mercurio", mass: 200.592, period: 6, group: 12, block: "d", category: "metal-transicion", electronegativity: 2.00, atomicRadius: 171, atomicVolume: 14.8, ionizationEnergy: 1007, electronAffinity: -48, electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s²", valenceElectrons: 2, typicalBond: "metálico", dataQuality: { electronAffinity: "experimental" } },
  { z: 81, symbol: "Tl", name: "Talio", mass: 204.383, period: 6, group: 13, block: "p", category: "metal-post-transicion", electronegativity: 1.62, atomicRadius: 156, atomicVolume: 17.2, ionizationEnergy: 589, electronAffinity: 36.4, electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹", valenceElectrons: 3, typicalBond: "metálico" },
  { z: 82, symbol: "Pb", name: "Plomo", mass: 207.200, period: 6, group: 14, block: "p", category: "metal-post-transicion", electronegativity: 2.33, atomicRadius: 154, atomicVolume: 18.3, ionizationEnergy: 716, electronAffinity: 35.1, electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²", valenceElectrons: 4, typicalBond: "metálico" },
  { z: 83, symbol: "Bi", name: "Bismuto", mass: 208.980, period: 6, group: 15, block: "p", category: "metal-post-transicion", electronegativity: 2.02, atomicRadius: 143, atomicVolume: 21.3, ionizationEnergy: 703, electronAffinity: 91.2, electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³", valenceElectrons: 5, typicalBond: "metálico" },
  { z: 84, symbol: "Po", name: "Polonio", mass: 209.000, period: 6, group: 16, block: "p", category: "metaloide", electronegativity: 2.00, atomicRadius: 135, atomicVolume: 22.7, ionizationEnergy: 812, electronAffinity: 183.3, electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴", valenceElectrons: 6, typicalBond: "covalente" },
  { z: 85, symbol: "At", name: "Astato", mass: 210.000, period: 6, group: 17, block: "p", category: "halogeno", electronegativity: 2.20, atomicRadius: 127, atomicVolume: 30.0, ionizationEnergy: 920, electronAffinity: 270.1, electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵", valenceElectrons: 7, typicalBond: "iónico", dataQuality: { atomicVolume: "estimado" } },
  { z: 86, symbol: "Rn", name: "Radón", mass: 222.000, period: 6, group: 18, block: "p", category: "gas-noble", electronegativity: null, atomicRadius: 120, atomicVolume: 50.5, ionizationEnergy: 1037, electronAffinity: -68, electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶", valenceElectrons: 8, typicalBond: "ninguno", dataQuality: { electronAffinity: "experimental" } },

  // ─── Período 7 ────────────────────────────────────────────────────────────
  // NOTA: Para Z=89–118, los valores de radio atómico, electronegatividad y
  // energía de ionización marcados como "estimación teórica" provienen de
  // IUPAC 2021, Pyykkö (2009) y literatura especializada en elementos
  // superpesados. No deben usarse como valores experimentales confirmados.
  { z: 87, symbol: "Fr", name: "Francio", mass: 223.000, period: 7, group: 1, block: "s", category: "metal-alcalino", electronegativity: 0.70, atomicRadius: 260, atomicVolume: 70.0, ionizationEnergy: 393, electronAffinity: 44, electronConfig: "[Rn] 7s¹", valenceElectrons: 1, typicalBond: "iónico", dataQuality: { electronAffinity: "estimado" } }, // atomicVolume: estimación extrapolada por tendencia Grupo 1
  { z: 88, symbol: "Ra", name: "Radio", mass: 226.000, period: 7, group: 2, block: "s", category: "metal-alcalinoterreo", electronegativity: 0.90, atomicRadius: 221, atomicVolume: 45.2, ionizationEnergy: 509, electronAffinity: 9.6, electronConfig: "[Rn] 7s²", valenceElectrons: 2, typicalBond: "iónico", dataQuality: { electronAffinity: "estimado" } },
  // Actinides (period 7, f-block)
  { z: 89, symbol: "Ac", name: "Actinio", mass: 227.000, period: 7, group: null, block: "f", category: "actinido", electronegativity: 1.10, atomicRadius: 215, atomicVolume: 22.5, ionizationEnergy: 499, electronAffinity: 33, electronConfig: "[Rn] 6d¹ 7s²", valenceElectrons: 3, typicalBond: "metálico", dataQuality: { electronAffinity: "estimado" } },
  { z: 90, symbol: "Th", name: "Torio", mass: 232.038, period: 7, group: null, block: "f", category: "actinido", electronegativity: 1.30, atomicRadius: 206, atomicVolume: 19.9, ionizationEnergy: 587, electronAffinity: 112, electronConfig: "[Rn] 6d² 7s²", valenceElectrons: 4, typicalBond: "metálico", dataQuality: { electronAffinity: "estimado" } },
  { z: 91, symbol: "Pa", name: "Protactinio", mass: 231.036, period: 7, group: null, block: "f", category: "actinido", electronegativity: 1.50, atomicRadius: 200, atomicVolume: 15.0, ionizationEnergy: 568, electronAffinity: 53, electronConfig: "[Rn] 5f² 6d¹ 7s²", valenceElectrons: 5, typicalBond: "metálico", dataQuality: { electronAffinity: "estimado" } },
  { z: 92, symbol: "U", name: "Uranio", mass: 238.029, period: 7, group: null, block: "f", category: "actinido", electronegativity: 1.38, atomicRadius: 196, atomicVolume: 12.5, ionizationEnergy: 598, electronAffinity: 51, electronConfig: "[Rn] 5f³ 6d¹ 7s²", valenceElectrons: 6, typicalBond: "metálico", dataQuality: { electronAffinity: "estimado" } },
  { z: 93, symbol: "Np", name: "Neptunio", mass: 237.000, period: 7, group: null, block: "f", category: "actinido", electronegativity: 1.36, atomicRadius: 190, atomicVolume: 11.6, ionizationEnergy: 605, electronAffinity: 46, electronConfig: "[Rn] 5f⁴ 6d¹ 7s²", valenceElectrons: 5, typicalBond: "metálico", dataQuality: { electronAffinity: "estimado" } },
  { z: 94, symbol: "Pu", name: "Plutonio", mass: 244.000, period: 7, group: null, block: "f", category: "actinido", electronegativity: 1.28, atomicRadius: 187, atomicVolume: 12.3, ionizationEnergy: 585, electronAffinity: -48, electronConfig: "[Rn] 5f⁶ 7s²", valenceElectrons: 4, typicalBond: "metálico", dataQuality: { electronAffinity: "estimado" } },
  { z: 95, symbol: "Am", name: "Americio", mass: 243.000, period: 7, group: null, block: "f", category: "actinido", electronegativity: 1.13, atomicRadius: 180, atomicVolume: 20.3, ionizationEnergy: 578, electronAffinity: -9, electronConfig: "[Rn] 5f⁷ 7s²", valenceElectrons: 3, typicalBond: "metálico", dataQuality: { atomicVolume: "experimental", electronAffinity: "estimado" } }, // electronegativity: estimación teórica
  { z: 96, symbol: "Cm", name: "Curio", mass: 247.000, period: 7, group: null, block: "f", category: "actinido", electronegativity: 1.28, atomicRadius: 169, atomicVolume: 18.3, ionizationEnergy: 581, electronAffinity: -97, electronConfig: "[Rn] 5f⁷ 6d¹ 7s²", valenceElectrons: 3, typicalBond: "metálico", dataQuality: { atomicVolume: "experimental", electronAffinity: "estimado" } }, // electronegativity: estimación teórica
  { z: 97, symbol: "Bk", name: "Berkelio", mass: 247.000, period: 7, group: null, block: "f", category: "actinido", electronegativity: 1.30, atomicRadius: 168, atomicVolume: 16.7, ionizationEnergy: 601, electronAffinity: -165, electronConfig: "[Rn] 5f⁹ 7s²", valenceElectrons: 3, typicalBond: "metálico", dataQuality: { atomicVolume: "experimental", electronAffinity: "estimado" } }, // electronegativity: estimación teórica
  { z: 98, symbol: "Cf", name: "Californio", mass: 251.000, period: 7, group: null, block: "f", category: "actinido", electronegativity: 1.30, atomicRadius: 168, atomicVolume: 16.6, ionizationEnergy: 608, electronAffinity: -97, electronConfig: "[Rn] 5f¹⁰ 7s²", valenceElectrons: 3, typicalBond: "metálico", dataQuality: { atomicVolume: "experimental", electronAffinity: "estimado" } }, // electronegativity: estimación teórica
  { z: 99, symbol: "Es", name: "Einstenio", mass: 252.000, period: 7, group: null, block: "f", category: "actinido", electronegativity: 1.30, atomicRadius: 165, atomicVolume: 28.5, ionizationEnergy: 619, electronAffinity: -28, electronConfig: "[Rn] 5f¹¹ 7s²", valenceElectrons: 3, typicalBond: "metálico", dataQuality: { atomicVolume: "estimado", electronAffinity: "estimado" } }, // electronegativity: estimación teórica
  { z: 100, symbol: "Fm", name: "Fermio", mass: 257.000, period: 7, group: null, block: "f", category: "actinido", electronegativity: 1.30, atomicRadius: 167, atomicVolume: 26.5, ionizationEnergy: 627, electronAffinity: -34, electronConfig: "[Rn] 5f¹² 7s²", valenceElectrons: 3, typicalBond: "metálico", dataQuality: { atomicVolume: "estimado", electronAffinity: "estimado" } }, // electronegativity: estimación teórica
  { z: 101, symbol: "Md", name: "Mendelevio", mass: 258.000, period: 7, group: null, block: "f", category: "actinido", electronegativity: 1.30, atomicRadius: 173, atomicVolume: 25.0, ionizationEnergy: 635, electronAffinity: -34, electronConfig: "[Rn] 5f¹³ 7s²", valenceElectrons: 3, typicalBond: "metálico", dataQuality: { atomicVolume: "estimado", electronAffinity: "estimado" } }, // electronegativity: estimación teórica
  { z: 102, symbol: "No", name: "Nobelio", mass: 259.000, period: 7, group: null, block: "f", category: "actinido", electronegativity: 1.30, atomicRadius: 176, atomicVolume: 26.2, ionizationEnergy: 642, electronAffinity: -223, electronConfig: "[Rn] 5f¹⁴ 7s²", valenceElectrons: 3, typicalBond: "metálico", dataQuality: { atomicVolume: "estimado", electronAffinity: "estimado" } }, // electronegativity: estimación teórica
  { z: 103, symbol: "Lr", name: "Lawrencio", mass: 262.000, period: 7, group: null, block: "f", category: "actinido", electronegativity: 1.30, atomicRadius: 161, atomicVolume: 16.8, ionizationEnergy: 478, electronAffinity: -30, electronConfig: "[Rn] 5f¹⁴ 7s² 7p¹", valenceElectrons: 3, typicalBond: "metálico", dataQuality: { atomicVolume: "estimado", electronAffinity: "estimado" } }, // electronegativity: estimación teórica
  { z: 104, symbol: "Rf", name: "Rutherfordio", mass: 267.000, period: 7, group: 4, block: "d", category: "metal-transicion", electronegativity: null, atomicRadius: 157, atomicVolume: null, ionizationEnergy: 580, electronAffinity: null, electronConfig: "[Rn] 5f¹⁴ 6d² 7s²", valenceElectrons: 4, typicalBond: "metálico" },
  { z: 105, symbol: "Db", name: "Dubnio", mass: 268.000, period: 7, group: 5, block: "d", category: "metal-transicion", electronegativity: null, atomicRadius: 149, atomicVolume: null, ionizationEnergy: 665, electronAffinity: null, electronConfig: "[Rn] 5f¹⁴ 6d³ 7s²", valenceElectrons: 5, typicalBond: "metálico" }, // estimación teórica
  { z: 106, symbol: "Sg", name: "Seaborgio", mass: 271.000, period: 7, group: 6, block: "d", category: "metal-transicion", electronegativity: null, atomicRadius: 143, atomicVolume: null, ionizationEnergy: 757, electronAffinity: null, electronConfig: "[Rn] 5f¹⁴ 6d⁴ 7s²", valenceElectrons: 6, typicalBond: "metálico" }, // estimación teórica
  { z: 107, symbol: "Bh", name: "Bohrio", mass: 272.000, period: 7, group: 7, block: "d", category: "metal-transicion", electronegativity: null, atomicRadius: 141, atomicVolume: null, ionizationEnergy: 740, electronAffinity: null, electronConfig: "[Rn] 5f¹⁴ 6d⁵ 7s²", valenceElectrons: 7, typicalBond: "metálico" }, // estimación teórica
  { z: 108, symbol: "Hs", name: "Hassio", mass: 270.000, period: 7, group: 8, block: "d", category: "metal-transicion", electronegativity: null, atomicRadius: 134, atomicVolume: null, ionizationEnergy: 730, electronAffinity: null, electronConfig: "[Rn] 5f¹⁴ 6d⁶ 7s²", valenceElectrons: 8, typicalBond: "metálico" }, // estimación teórica
  { z: 109, symbol: "Mt", name: "Meitnerio", mass: 276.000, period: 7, group: 9, block: "d", category: "metal-transicion", electronegativity: null, atomicRadius: 129, atomicVolume: null, ionizationEnergy: 800, electronAffinity: null, electronConfig: "[Rn] 5f¹⁴ 6d⁷ 7s²", valenceElectrons: 9, typicalBond: "metálico" }, // estimación teórica
  { z: 110, symbol: "Ds", name: "Darmstadtio", mass: 281.000, period: 7, group: 10, block: "d", category: "metal-transicion", electronegativity: null, atomicRadius: 128, atomicVolume: null, ionizationEnergy: 1014, electronAffinity: null, electronConfig: "[Rn] 5f¹⁴ 6d⁹ 7s¹", valenceElectrons: 2, typicalBond: "metálico" }, // estimación teórica
  { z: 111, symbol: "Rg", name: "Roentgenio", mass: 280.000, period: 7, group: 11, block: "d", category: "metal-transicion", electronegativity: null, atomicRadius: 121, atomicVolume: null, ionizationEnergy: 1020, electronAffinity: null, electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s¹", valenceElectrons: 1, typicalBond: "metálico" }, // estimación teórica
  { z: 112, symbol: "Cn", name: "Copernicio", mass: 285.000, period: 7, group: 12, block: "d", category: "metal-transicion", electronegativity: null, atomicRadius: 122, atomicVolume: null, ionizationEnergy: 1155, electronAffinity: null, electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s²", valenceElectrons: 2, typicalBond: "metálico" }, // estimación teórica
  { z: 113, symbol: "Nh", name: "Nihonio", mass: 284.000, period: 7, group: 13, block: "p", category: "metal-post-transicion", electronegativity: null, atomicRadius: 136, atomicVolume: null, ionizationEnergy: 705, electronAffinity: null, electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹", valenceElectrons: 3, typicalBond: "metálico" }, // estimación teórica
  { z: 114, symbol: "Fl", name: "Flerovio", mass: 289.000, period: 7, group: 14, block: "p", category: "metal-post-transicion", electronegativity: null, atomicRadius: 143, atomicVolume: null, ionizationEnergy: 832, electronAffinity: null, electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²", valenceElectrons: 4, typicalBond: "metálico" }, // estimación teórica
  { z: 115, symbol: "Mc", name: "Moscovio", mass: 288.000, period: 7, group: 15, block: "p", category: "metal-post-transicion", electronegativity: null, atomicRadius: 162, atomicVolume: null, ionizationEnergy: 538, electronAffinity: null, electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³", valenceElectrons: 5, typicalBond: "metálico" }, // estimación teórica
  { z: 116, symbol: "Lv", name: "Livermorio", mass: 293.000, period: 7, group: 16, block: "p", category: "metal-post-transicion", electronegativity: null, atomicRadius: 175, atomicVolume: null, ionizationEnergy: 663, electronAffinity: null, electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴", valenceElectrons: 6, typicalBond: "metálico" }, // estimación teórica
  { z: 117, symbol: "Ts", name: "Teneso", mass: 294.000, period: 7, group: 17, block: "p", category: "halogeno", electronegativity: null, atomicRadius: 165, atomicVolume: null, ionizationEnergy: 736, electronAffinity: null, electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵", valenceElectrons: 7, typicalBond: "iónico" }, // estimación teórica
  { z: 118, symbol: "Og", name: "Oganesón", mass: 294.000, period: 7, group: 18, block: "p", category: "gas-noble", electronegativity: null, atomicRadius: 157, atomicVolume: null, ionizationEnergy: 860, electronAffinity: null, electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶", valenceElectrons: 8, typicalBond: "ninguno" }, // estimación teórica
];
